In [1]:
# 可参考thesis data analyse 或者1.数据预处理
import pandas as pd
import numpy as np

In [5]:
# 全模式
import jieba
seg_list = jieba.cut("商品质量无可挑剔，价格亲民，真是物超所值", cut_all=True)
print("【全模式】：" + "/ ".join(seg_list))

【全模式】：商品/ 商品质量/ 品质/ 质量/ 无可/ 无可挑剔/ 挑剔/ ，/ 价格/ 亲/ 民/ ，/ 真是/ 物超所值

In [6]:
# 精确模式
seg_list = jieba.cut("商品质量无可挑剔，价格亲民，真是物超所值", cut_all=False)
print("【精确模式】：" + "/ ".join(seg_list))

【精确模式】：商品质量/ 无可挑剔/ ，/ 价格/ 亲民/ ，/ 真是/ 物超所值

In [7]:
# 搜索引擎模式
seg_list = jieba.cut_for_search("商品质量无可挑剔，价格亲民，真是物超所值")  
print("【搜索引擎模式】：" + "/ ".join(seg_list))

【搜索引擎模式】：商品/ 品质/ 质量/ 商品质量/ 无可/ 挑剔/ 无可挑剔/ ，/ 价格/ 亲民/ ，/ 真是/ 物超所值

In [2]:
# 导入测试数据
test1000 = pd.read_excel('./train/content_train_mark - 1000.xlsx')
test1000

,商品名称,评论,评价星级,情感
0,MatePad Pro 13.2 2025,外观材质：非常高档\n屏幕效果：提升很大，适合网课办公\n运行速度：鸿蒙系统值得尝试\n轻薄...,star5,pos
1,小米Redmi Pad Pro,小米 Redmi Pad Pro 。外观很漂亮，开机后色彩艳丽，不刺眼。12.1英寸屏，感觉...,star5,pos
2,小米7,在华为和小米之间犹豫，最后还是选了小米，手感不错，我一般是娱乐多些，看电影还是不错的，运行起...,star5,pos
3,MatePad Pro 13.2 2025,买了平板，真的很好用，屏幕大又清晰，看剧玩游戏特别爽。而且速度超快，用起来一点也不卡。携带也...,star5,pos
4,iPad Pro 11,要不要背刺我，买完没多久又降价🥶🥶🥶\n,star2,neg
...,...,...,...,...
1104,MatePad Pro 13.2 2025,要全不是pc级办公，买回来还需要报名升级，升级需要等14 天，这到时候发现有问题退都不退不了...,star1,neg
1105,MatePad Pro 13.2,一个月降400。赠品还都补发。\n,star1,neg
1106,小米Redmi Pad Pro,为什么刚买上就便宜100\n,star1,neg
1107,iPad Pro 13,运行速度：很快\n轻薄程度：非常薄而且担心会弯屏\n屏幕效果：时间久眼睛会累\n,star4,neg
1108,iPad mini (A17 Pro),东西挺好的，就是今天有一个自称京东的客服，来推销延保服务什么的？我的信息被外泄了！感觉很不好。\n,star3,neg

In [3]:
import re

# 去除英文、数字、表情等
# 由于评论主要为京东平板电脑的评论，因此去除这些词语
strinfo = re.compile('[0-9a-zA-Z]|京东|平板|平板电脑|苹果|华为|小米|电脑') # 定义正则表达式字符串strinfo，用于匹配小写字母、大写字母、京东、平板、平板电脑

# 定义正则表达式字符串emoji_pattern，用于去除emoji表情符号
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F700-\U0001F77F"  # alchemical symbols
                           u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                           u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                           u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                           u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"  # Dingbats
                           u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                           u"\u2600-\u2B55"
                           "]+", flags=re.UNICODE)

# 定义正则表达式字符串emoji_pattern，用于去除emoji表情符号
emoticons_pattern = re.compile(r"""
                                [\^\-\+_@<>/\\\(\)\（\）\[\]{}○●♡♥☆★✧=~|*‿っツ＾∀･ω･´∀｀๑وㅂ•̀•́·｡ﾉ]
                                (?:                                                 
                                    [\^\-\+_@<>/\\\(\)\（\）\[\]{}○●♡♥☆★✧=~|*‿っツ＾∀･ω･´∀｀๑وㅂ•̀•́·｡ﾉ]
                                )*
                                """, re.VERBOSE | re.UNICODE)
# 定义正则表达式字符串punct_pattern，用于去除标点符号和回车
punct_pattern = re.compile(r'[,.!?"\'。，！？“”:：]|\n')

content0 = test1000["评论"]
content1 = content0.apply(lambda x: strinfo.sub('', x)) # sub函数，用空值替换所有匹配项
content2 = content1.apply(lambda x: emoji_pattern.sub('', x))
content3 = content2.apply(lambda x: emoticons_pattern.sub('', x))
content3

0       外观材质：非常高档\n屏幕效果：提升很大，适合网课办公\n运行速度：鸿蒙系统值得尝试\n轻薄...
1           。外观很漂亮，开机后色彩艳丽，不刺眼。.英寸屏，感觉跟个小笔记本一样了。安装的是澎湃...
2       在和之间犹豫，最后还是选了，手感不错，我一般是娱乐多些，看电影还是不错的，运行起来也很流畅，...
3       买了，真的很好用，屏幕大又清晰，看剧玩游戏特别爽。而且速度超快，用起来一点也不卡。携带也方便...
4                                       要不要背刺我，买完没多久又降价\n
                              ...
1104    要全不是级办公，买回来还需要报名升级，升级需要等 天，这到时候发现有问题退都不退不了，根本就...
1105                                       一个月降。赠品还都补发。\n
1106                                          为什么刚买上就便宜\n
1107             运行速度：很快\n轻薄程度：非常薄而且担心会弯屏\n屏幕效果：时间久眼睛会累\n
1108      东西挺好的，就是今天有一个自称的客服，来推销延保服务什么的？我的信息被外泄了！感觉很不好。\n
Name: 评论, Length: 1109, dtype: object

In [4]:
# 分词
import jieba.posseg as psg # 导入jieba中文分词库（包含词性）

# 自定义简单分词函数worker，jieba.cut(s) 精确模式：把文本精确切分开，不存在冗余单词。获得分词结果的同时标注词性
worker = lambda s: [(x.word, x.flag) for x in psg.cut(s)]
seg_word = content3.apply(worker) # 对评论内容content列进行分析和标注词性
seg_word

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Jessie\AppData\Local\Temp\jieba.cache
Loading model cost 0.972 seconds.
Prefix dict has been built successfully.

0       [(外观, n), (材质, n), (：, x), (非常, d), (高档, b), (...
1       [( , x), ( , x), ( , x), ( , x), (。, x), (外观, ...
2       [(在, p), (和, c), (之间, f), (犹豫, a), (，, x), (最后...
3       [(买, v), (了, ul), (，, x), (真的, d), (很好, d), (用...
4       [(要, v), (不要, df), (背, v), (刺, v), (我, r), (，,...
                              ...
1104    [(要, v), (全, n), (不是, c), (级, q), (办公, n), (，,...
1105    [(一个月, m), (降, v), (。, x), (赠品, n), (还, d), (都...
1106    [(为什么, r), (刚, d), (买, v), (上, f), (就, d), (便宜...
1107    [(运行, v), (速度, n), (：, x), (很快, d), (\n, x), (...
1108    [(东西, ns), (挺, d), (好, a), (的, uj), (，, x), (就...
Name: 评论, Length: 1109, dtype: object

In [5]:
# 将词语转为数据框形式，一列是词，一列是词语所在的句子ID（index_content），一列是词语在该句子的位置（index_word）
n_word = seg_word.apply(lambda x: len(x))  # 每一评论中词的个数，组成列表。
n_content = [[x+1]*y for x,y in zip(list(seg_word.index), list(n_word))] # 将评论索引和评论的词语数量一一配对，为每个分词构造所在评论的id
# [x+1]*y：生成一个长度为 y 的列表，列表中的每个元素是 x+1
# n_content为嵌套列表
index_content = sum(n_content, [])  # 将嵌套的列表展开为扁平列表，作为词所在评论的id。[]是初始值

In [6]:
# 词性标注
seg_word = sum(seg_word, [])
word = [x[0] for x in seg_word]  # 词
nature = [x[1] for x in seg_word]  # 词性

In [7]:
product = [[x]*y for x,y in zip(list(test1000['商品名称']), list(n_word))]
product = sum(product, [])  # 商品名称

In [8]:
sentiment = [[x]*y for x,y in zip(list(test1000['情感']), list(n_word))]
sentiment = sum(sentiment, []) #评价星级

In [9]:
result = pd.DataFrame({"index_content":index_content, 
                       "product":product,
                       "sentiment": sentiment,
                       "word":word,
                       "nature":nature}) # 得到分词、词性标注后的结果
result

       index_content                product sentiment word nature
0                  1  MatePad Pro 13.2 2025       pos   外观      n
1                  1  MatePad Pro 13.2 2025       pos   材质      n
2                  1  MatePad Pro 13.2 2025       pos    ：      x
3                  1  MatePad Pro 13.2 2025       pos   非常      d
4                  1  MatePad Pro 13.2 2025       pos   高档      b
...              ...                    ...       ...  ...    ...
58982           1109    iPad mini (A17 Pro)       neg   感觉      n
58983           1109    iPad mini (A17 Pro)       neg    很     zg
58984           1109    iPad mini (A17 Pro)       neg   不好      d
58985           1109    iPad mini (A17 Pro)       neg    。      x
58986           1109    iPad mini (A17 Pro)       neg   \n      x

[58987 rows x 5 columns]

In [10]:
# 删除标点符号
result = result[result['nature'] != 'x']  # x表示标点符号
result

       index_content                product sentiment word nature
0                  1  MatePad Pro 13.2 2025       pos   外观      n
1                  1  MatePad Pro 13.2 2025       pos   材质      n
3                  1  MatePad Pro 13.2 2025       pos   非常      d
4                  1  MatePad Pro 13.2 2025       pos   高档      b
6                  1  MatePad Pro 13.2 2025       pos   屏幕      n
...              ...                    ...       ...  ...    ...
58979           1109    iPad mini (A17 Pro)       neg   外泄      v
58980           1109    iPad mini (A17 Pro)       neg    了     ul
58982           1109    iPad mini (A17 Pro)       neg   感觉      n
58983           1109    iPad mini (A17 Pro)       neg    很     zg
58984           1109    iPad mini (A17 Pro)       neg   不好      d

[45372 rows x 5 columns]

In [11]:
# 去除停用词
stop_path = open(r'./edited_stopwords.txt', 'r',encoding='UTF-8') # 导入停用词词典,'r'只读
stop = stop_path.readlines() # 读取行并作为字符串列表返回
stop = [x.replace('\n', '') for x in stop] # 用空格替换\n换行符
word = list(set(word) - set(stop)) # 首先构造词和停用词的无序无重复set集合，然后在词的set中去除停用词的set
result = result[result['word'].isin(word)] # 从词中去除停用词，并更新result表格
result

       index_content                product sentiment word nature
0                  1  MatePad Pro 13.2 2025       pos   外观      n
1                  1  MatePad Pro 13.2 2025       pos   材质      n
4                  1  MatePad Pro 13.2 2025       pos   高档      b
6                  1  MatePad Pro 13.2 2025       pos   屏幕      n
7                  1  MatePad Pro 13.2 2025       pos   效果      n
...              ...                    ...       ...  ...    ...
58971           1109    iPad mini (A17 Pro)       neg   服务     vn
58977           1109    iPad mini (A17 Pro)       neg   信息      n
58979           1109    iPad mini (A17 Pro)       neg   外泄      v
58982           1109    iPad mini (A17 Pro)       neg   感觉      n
58984           1109    iPad mini (A17 Pro)       neg   不好      d

[26880 rows x 5 columns]

In [12]:
# 构造各词在对应评论的位置列（添加到最后一列）
n_word = list(result.groupby(by = ['index_content'])['index_content'].count()) # 对去除停用词后的result重新计数
index_word = [list(np.arange(0, y)) for y in n_word] # 为每条评论中的词指定在该评论中的id
index_word = sum(index_word, [])  # 合并成一列

In [13]:
# 合并评论id，评论中词的id，词，词性，评论类型
result['index_word'] = index_word # 添加index_word一列到原表格的最右一列
result

C:\Users\Jessie\AppData\Local\Temp\ipykernel_16884\999823848.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['index_word'] = index_word # 添加index_word一列到原表格的最右一列

       index_content                product sentiment word nature  index_word
0                  1  MatePad Pro 13.2 2025       pos   外观      n           0
1                  1  MatePad Pro 13.2 2025       pos   材质      n           1
4                  1  MatePad Pro 13.2 2025       pos   高档      b           2
6                  1  MatePad Pro 13.2 2025       pos   屏幕      n           3
7                  1  MatePad Pro 13.2 2025       pos   效果      n           4
...              ...                    ...       ...  ...    ...         ...
58971           1109    iPad mini (A17 Pro)       neg   服务     vn           6
58977           1109    iPad mini (A17 Pro)       neg   信息      n           7
58979           1109    iPad mini (A17 Pro)       neg   外泄      v           8
58982           1109    iPad mini (A17 Pro)       neg   感觉      n           9
58984           1109    iPad mini (A17 Pro)       neg   不好      d          10

[26880 rows x 6 columns]

In [14]:
# 重新编号
result = result.reset_index(drop=True)
result

       index_content                product sentiment word nature  index_word
0                  1  MatePad Pro 13.2 2025       pos   外观      n           0
1                  1  MatePad Pro 13.2 2025       pos   材质      n           1
2                  1  MatePad Pro 13.2 2025       pos   高档      b           2
3                  1  MatePad Pro 13.2 2025       pos   屏幕      n           3
4                  1  MatePad Pro 13.2 2025       pos   效果      n           4
...              ...                    ...       ...  ...    ...         ...
26875           1109    iPad mini (A17 Pro)       neg   服务     vn           6
26876           1109    iPad mini (A17 Pro)       neg   信息      n           7
26877           1109    iPad mini (A17 Pro)       neg   外泄      v           8
26878           1109    iPad mini (A17 Pro)       neg   感觉      n           9
26879           1109    iPad mini (A17 Pro)       neg   不好      d          10

[26880 rows x 6 columns]

In [15]:
# 读入正面、负面情感评价词
pos_comment = pd.read_csv("./data/正面评价词语（中文）.txt", header=None,sep="/n", encoding = 'utf-8', engine='python') # header=none是一种文件读取模式,用于读取没有列标题的文件。sep=’ ‘： 表示当输入多个打印的值时，各个值之间分割方式，默认空格，可以自定义，/n为换行符。
neg_comment = pd.read_csv("./data/负面评价词语（中文）.txt", header=None,sep="/n", encoding = 'utf-8', engine='python')
pos_emotion = pd.read_csv("./data/正面情感词语（中文）.txt", header=None,sep="/n", encoding = 'utf-8', engine='python')
neg_emotion = pd.read_csv("./data/负面情感词语（中文）.txt", header=None,sep="/n", encoding = 'utf-8', engine='python')

In [16]:
# 合并情感词与评价词
positive = set(pos_comment.iloc[:,0])|set(pos_emotion.iloc[:,0])
negative = set(neg_comment.iloc[:,0])|set(neg_emotion.iloc[:,0])
intersection = positive & negative  # 正负面情感词表中相同的词语
positive = list(positive - intersection) # 剔除正负面情感词中共同含有的有争议词
negative = list(negative - intersection)

positive = pd.DataFrame({"word":positive,
                         "weight":[1]*len(positive)})
negative = pd.DataFrame({"word":negative,
                         "weight":[-1]*len(negative)}) 

posneg = pd.concat([positive,negative]) # pd.concat拼接函数。

posneg

      word  weight
0     虚怀若谷       1
1     熙熙攘攘       1
2     郁郁苍苍       1
3       款洽       1
4     实心实意       1
...    ...     ...
4232   瞧不起      -1
4233    嶙嶙      -1
4234  精神溜号      -1
4235  漫不经意      -1
4236  愚不可及      -1

[8668 rows x 2 columns]

In [17]:
#  将分词结果与正负面情感词表合并，定位情感词
data_posneg = posneg.merge(result, left_on = 'word', right_on = 'word', how = 'right') # how: 合并方式，可选值包括"inner"、"outer"、"left"和"right"，分别对应内连接、外连接、左连接和右连接。默认为"inner"。
data_posneg = data_posneg.sort_values(by = ['index_content','index_word'])
data_posneg

,word,weight,index_content,product,sentiment,nature,index_word
0,外观,NaN,1,MatePad Pro 13.2 2025,pos,n,0
1,材质,NaN,1,MatePad Pro 13.2 2025,pos,n,1
2,高档,1.0,1,MatePad Pro 13.2 2025,pos,b,2
3,屏幕,NaN,1,MatePad Pro 13.2 2025,pos,n,3
4,效果,NaN,1,MatePad Pro 13.2 2025,pos,n,4
...,...,...,...,...,...,...,...
26875,服务,NaN,1109,iPad mini (A17 Pro),neg,vn,6
26876,信息,NaN,1109,iPad mini (A17 Pro),neg,n,7
26877,外泄,NaN,1109,iPad mini (A17 Pro),neg,v,8
26878,感觉,NaN,1109,iPad mini (A17 Pro),neg,n,9
26879,不好,-1.0,1109,iPad mini (A17 Pro),neg,d,10

In [18]:
# 根据情感词前时候有否定词或双层否定词对情感值进行修正
# 载入否定词表
notdict = pd.read_csv("./data/not.csv")
notdict

   term
0     不
1     没
2     无
3     非
4     莫
5     弗
6     毋
7     勿
8     未
9     否
10    别
11    無
12    休
13   不是
14   不能
15   不可
16   没有
17   不用
18   不要
19   从没
20   不太

In [19]:
# 处理否定修饰词
data_posneg['amend_weight'] = data_posneg['weight']  # 构造新列，作为经过否定词修正后的情感值
data_posneg['id'] = np.arange(0, len(data_posneg))
only_inclination = data_posneg.dropna()  # 只保留有情感值的词语。.dropna() 是 pandas 库中 DataFrame 和 Series 对象的一个方法，用于删除包含缺失值的行或列
only_inclination.index = np.arange(0, len(only_inclination))
index = only_inclination['id']

for i in np.arange(0, len(only_inclination)):
    review = data_posneg[data_posneg['index_content'] == only_inclination['index_content'][i]]  # 提取第i个情感词所在的评论
    review.index = np.arange(0, len(review))
    affective = only_inclination['index_word'][i]  # 第i个情感值在该评论中的位置
    if affective == 1:
        ne = sum([i in notdict['term'] for i in review['word'][affective - 1]]) # 当目标分词位于第二位，则考察第一位的否定性。
        if ne == 1: # 当前面有1个否定词，则更改分数为相反数。
            data_posneg['amend_weight'][index[i]] = - data_posneg['weight'][index[i]]          
    elif affective > 1: #当目标分词位于第三位及之后，则考察前两位的否定性。
        ne = sum([i in notdict['term'] for i in review['word'][[affective - 1, 
                  affective - 2]]])
        if ne == 1:  # 当前面两个分词中有1个否定词，则更改分数为相反数。
            data_posneg['amend_weight'][index[i]] = - data_posneg['weight'][index[i]]

In [20]:
# 更新只保留情感值的数据
only_inclination = only_inclination.dropna()

In [21]:
# 计算每条评论的情感值
emotional_value = only_inclination.groupby(['index_content'],as_index=False)['amend_weight'].sum() 
# as_index: 分组结果默认将分组列的值作为索引，如果按单列分组，结果默认是单索引，如果按多列分组，结果默认是多重索引。将as_index设置为False可以重置索引（0,1...）。

In [22]:
# 去除情感值为0的评论
emotional_value = emotional_value[emotional_value['amend_weight'] != 0]
emotional_value

      index_content  amend_weight
0                 1           3.0
1                 3           3.0
2                 4           3.0
3                 6           4.0
4                 7           4.0
...             ...           ...
1059           1099           1.0
1061           1101           2.0
1064           1107           2.0
1065           1108          -2.0
1066           1109          -1.0

[1018 rows x 2 columns]

In [23]:
# 给情感值大于0的赋予评论类型（content_type）为pos,小于0的为neg
emotional_value['a_type'] = ''
emotional_value['a_type'][emotional_value['amend_weight'] > 0] = 'pos'
emotional_value['a_type'][emotional_value['amend_weight'] < 0] = 'neg'
emotional_value

C:\Users\Jessie\AppData\Local\Temp\ipykernel_16884\1993566115.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  emotional_value['a_type'][emotional_value['amend_weight'] > 0] = 'pos'
C:\Users\Jessie\AppData\Local\Temp\ipykernel_16884\1993566115.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emotional_value['a_type'][emotional_value['amend_weight'] > 0] = 'pos'
C:\Users\Jessie\AppData\Local\Temp\ipykernel_16884\1993566115.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  emotional_value['a_type'][emotional_value['amend_weight'] < 0] = 'neg'
C:\Users\Jessie\AppData\Local\Temp\ipykernel_16884\1993566115.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emotional_value['a_type'][emotional_value['amend_weight'] < 0] = 'neg'

      index_content  amend_weight a_type
0                 1           3.0    pos
1                 3           3.0    pos
2                 4           3.0    pos
3                 6           4.0    pos
4                 7           4.0    pos
...             ...           ...    ...
1059           1099           1.0    pos
1061           1101           2.0    pos
1064           1107           2.0    pos
1065           1108          -2.0    neg
1066           1109          -1.0    neg

[1018 rows x 3 columns]

In [24]:
# 查看情感分析结果
result = emotional_value.merge(result, 
                               left_on = 'index_content', 
                               right_on = 'index_content',
                               how = 'left')
result = result[['index_content','sentiment', 'a_type']].drop_duplicates() 
result

       index_content sentiment a_type
0                  1       pos    pos
27                 3       pos    pos
44                 4       pos    pos
65                 6       pos    pos
83                 7       pos    pos
...              ...       ...    ...
25573           1099       neg    pos
25577           1101       neg    pos
25589           1107       neg    pos
25591           1108       neg    neg
25606           1109       neg    neg

[1018 rows x 3 columns]

In [25]:
count = np.sum(result['sentiment'] == result['a_type'])
print('准确率为：',count/len(result['sentiment']))

准确率为： 0.949901768172888

In [31]:
confusion_matrix = pd.crosstab(result['sentiment'], result['a_type'], margins=True)  # 制作混淆矩阵
confusion_matrix

a_type     neg  pos   All
sentiment
neg         22   36    58
pos         15  945   960
All         37  981  1018

In [32]:
print('基于词表的情感分析的准确率为：',(confusion_matrix.iat[0,0] + confusion_matrix.iat[1,1])/confusion_matrix.iat[2,2])

基于词表的情感分析的准确率为： 0.949901768172888