In [1]:
import pandas as pd # 以pd别名导入Python数据分析模块
import re # 导入正则表达式模块，可进行模式匹配、搜索和替换
import numpy as np # 导入数值计算模块
from sklearn.model_selection import train_test_split

# 随机抽取30% 进行人工标注

In [2]:
# 读取数据
reviews = pd.read_excel('./review/reviews_drdu.xlsx')
# 将特征（数据）划分到 X 中，标签划分到 Y 中
x = reviews[["商品名称","评论"]]
y = reviews["评价星级"]
# 使用train_test_split函数划分数据集(训练集占30%，测试集占70%)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7, random_state=0)

In [3]:
x_train

,商品名称,评论
9681,MatePad Pro 13.2,机身轻薄，运行流畅，看视频清晰，像是一个随身电视，随时追剧，看书、打游戏看视频都很OK，很开...
6602,MatePad 11.5 灵动款,外观材质：很漂亮\n屏幕效果：色彩效果好，清晰，屏幕\n运行速度：速度快\n轻薄程度：轻薄\...
12353,小米6Pro,Xiaomi Pad 6 Pro 真的太棒了!骁龙®️8+移动平台，安兔兔跑分超 110 万...
10467,MatePad Pro 13.2 2025,外观超级好看，非常纤薄，屏占比真的无敌了。屏幕素质非常好，天生绘画简直就是手残党的福音。\n
956,iPad 9,iPad，家里小朋友学习用，虽然是9代产品，但是足够用了，CPU严重性能过剩，就是容量大点就...
...,...,...
9225,MatePad Pro 12.2,华为mate pad pro 12.2英寸宣白设计优雅，12.2英寸全面屏视野广阔，色彩鲜艳...
13123,小米7,怎一个爽字了得，小米这次真的崛起了，一千多的平板性价比很高，3.2k的屏幕用来看国漫也太爽了...
9845,MatePad Pro 13.2,物流很快，物品完好无损，用起来很舒服，喜欢💕商品符合描述，显示效果很好，很纤细薄，反映很快，...
10799,MatePad Pro 13.2 2025,金色的外观设计十分出众，简约而不失时尚感。，背面还有纹路，不划手，很好看。\n屏幕显示效果很...
2732,iPad Air 13,大屏，高清，双十一活动期间买，价格不贵，比平时优惠很多。买给孩子学习英语使用，效果真是一级棒...

In [4]:
y_train

9681     star5
6602     star5
12353    star5
10467    star5
956      star5
         ...
9225     star5
13123    star5
9845     star5
10799    star5
2732     star5
Name: 评价星级, Length: 4966, dtype: object

In [5]:
content_train = x_train
content_train["评价星级"] = y_train
content_train

,商品名称,评论,评价星级
9681,MatePad Pro 13.2,机身轻薄，运行流畅，看视频清晰，像是一个随身电视，随时追剧，看书、打游戏看视频都很OK，很开...,star5
6602,MatePad 11.5 灵动款,外观材质：很漂亮\n屏幕效果：色彩效果好，清晰，屏幕\n运行速度：速度快\n轻薄程度：轻薄\...,star5
12353,小米6Pro,Xiaomi Pad 6 Pro 真的太棒了!骁龙®️8+移动平台，安兔兔跑分超 110 万...,star5
10467,MatePad Pro 13.2 2025,外观超级好看，非常纤薄，屏占比真的无敌了。屏幕素质非常好，天生绘画简直就是手残党的福音。\n,star5
956,iPad 9,iPad，家里小朋友学习用，虽然是9代产品，但是足够用了，CPU严重性能过剩，就是容量大点就...,star5
...,...,...,...
9225,MatePad Pro 12.2,华为mate pad pro 12.2英寸宣白设计优雅，12.2英寸全面屏视野广阔，色彩鲜艳...,star5
13123,小米7,怎一个爽字了得，小米这次真的崛起了，一千多的平板性价比很高，3.2k的屏幕用来看国漫也太爽了...,star5
9845,MatePad Pro 13.2,物流很快，物品完好无损，用起来很舒服，喜欢💕商品符合描述，显示效果很好，很纤细薄，反映很快，...,star5
10799,MatePad Pro 13.2 2025,金色的外观设计十分出众，简约而不失时尚感。，背面还有纹路，不划手，很好看。\n屏幕显示效果很...,star5
2732,iPad Air 13,大屏，高清，双十一活动期间买，价格不贵，比平时优惠很多。买给孩子学习英语使用，效果真是一级棒...,star5

In [6]:
content_train.to_excel('./train/content_train.xlsx', index = False)

# 人工标注完成后 upload标注好的文件 重启内核 分别提取neg、pos各457条

In [2]:
# 读取数据
content_train_mark = pd.read_excel('./train/content_train_420.xlsx')
content_train_mark

      评价星级                                               评价内容   情感
0    star2                           15天保价一过  直接便宜400块钱  受不了了  neg
1    star3                            23款的卖6千多接近7千元。\n价格有点优秀啊  neg
2    star1                                         30天价保，居然不保  neg
3    star1                                 3千多，就买了个裸机，没有膜和套送！  neg
4    star3  CPU真不行，这个价格也只能拿来看看视频和办公，游戏不指望了。再说一个很讨厌的地方——它的负...  neg
..     ...                                                ...  ...
832  star5  华为的平板真的吃不错，画质也很好，这种平板适合办公用，屏幕很大，音质也不错，拿着很大气，主要...  pos
833  star5  给女儿的生日礼物，人工智能让绘画、做学习笔记、思维导图更加便利小投入大产出，妥妥生产力工具。...  pos
834  star5  ipad10，基础款256G，时不时断货，颜色没有买到彩色的，买的银色的也很好看。最近有国补...  pos
835  star5  我是趁着补贴有优惠的时候果断下单mate pad Pro 13.2寸的，对于我这种喜好大屏幕...  pos
836  star5  小米粉 性价比级高的平板电脑 不重 用起来还是很丝滑的 给女朋友买的 她还是很开心的 非常满...  pos

[837 rows x 3 columns]

In [3]:
content_train_mark["评价内容"] = content_train_mark["评价内容"].apply(lambda x: re.sub("\n", "。", x))
content_train_mark

      评价星级                                               评价内容   情感
0    star2                           15天保价一过  直接便宜400块钱  受不了了  neg
1    star3                             23款的卖6千多接近7千元。。价格有点优秀啊  neg
2    star1                                         30天价保，居然不保  neg
3    star1                                 3千多，就买了个裸机，没有膜和套送！  neg
4    star3  CPU真不行，这个价格也只能拿来看看视频和办公，游戏不指望了。再说一个很讨厌的地方——它的负...  neg
..     ...                                                ...  ...
832  star5  华为的平板真的吃不错，画质也很好，这种平板适合办公用，屏幕很大，音质也不错，拿着很大气，主要...  pos
833  star5  给女儿的生日礼物，人工智能让绘画、做学习笔记、思维导图更加便利小投入大产出，妥妥生产力工具。...  pos
834  star5  ipad10，基础款256G，时不时断货，颜色没有买到彩色的，买的银色的也很好看。最近有国补...  pos
835  star5  我是趁着补贴有优惠的时候果断下单mate pad Pro 13.2寸的，对于我这种喜好大屏幕...  pos
836  star5  小米粉 性价比级高的平板电脑 不重 用起来还是很丝滑的 给女朋友买的 她还是很开心的 非常满...  pos

[837 rows x 3 columns]

In [4]:
# 分出负面评价
neg = content_train_mark[content_train_mark['情感'].str.contains('neg')]
neg_train = neg["评价内容"]

# 写入neg.txt
neg_train.to_csv('./train/neg.txt',sep='\n',index=False, header=False)

In [5]:
# 分出正面评价
pos = content_train_mark[content_train_mark['情感'].str.contains('pos')]
pos_train = pos["评价内容"]

# 写入neg.txt
pos_train.to_csv('./train/pos.txt',sep='\n',index=False, header=False)

# 训练测试snownlp

In [2]:
from snownlp import sentiment

pos = "./train/pos.txt"
neg = "./train/neg.txt"
sentiment.train(neg, pos)
sentiment.save("./train/sentiment.marshal2")
# 运行之后在同目录下会生成一个sentiment.marshal.3的文件

# 训练完毕后 下载sentiment.marshal3 保存到snownlp路径下 测试
## 一定记得备份原始sentiment.marshal3

In [2]:
# 测试模型效果，导入测试数据
import pandas as pd
test1000 = pd.read_excel('./train/content_train_mark - 1000.xlsx')
test1000

,商品名称,评论,评价星级,情感
0,MatePad Pro 13.2 2025,外观材质：非常高档\n屏幕效果：提升很大，适合网课办公\n运行速度：鸿蒙系统值得尝试\n轻薄...,star5,pos
1,小米Redmi Pad Pro,小米 Redmi Pad Pro 。外观很漂亮，开机后色彩艳丽，不刺眼。12.1英寸屏，感觉...,star5,pos
2,小米7,在华为和小米之间犹豫，最后还是选了小米，手感不错，我一般是娱乐多些，看电影还是不错的，运行起...,star5,pos
3,MatePad Pro 13.2 2025,买了平板，真的很好用，屏幕大又清晰，看剧玩游戏特别爽。而且速度超快，用起来一点也不卡。携带也...,star5,pos
4,iPad Pro 11,要不要背刺我，买完没多久又降价🥶🥶🥶\n,star2,neg
...,...,...,...,...
1104,MatePad Pro 13.2 2025,要全不是pc级办公，买回来还需要报名升级，升级需要等14 天，这到时候发现有问题退都不退不了...,star1,neg
1105,MatePad Pro 13.2,一个月降400。赠品还都补发。\n,star1,neg
1106,小米Redmi Pad Pro,为什么刚买上就便宜100\n,star1,neg
1107,iPad Pro 13,运行速度：很快\n轻薄程度：非常薄而且担心会弯屏\n屏幕效果：时间久眼睛会累\n,star4,neg
1108,iPad mini (A17 Pro),东西挺好的，就是今天有一个自称京东的客服，来推销延保服务什么的？我的信息被外泄了！感觉很不好。\n,star3,neg

In [3]:
from snownlp import SnowNLP
from snownlp import sentiment

In [4]:
s = []
for c in test1000['评论']:
    score = SnowNLP(c).sentiments
    if score>=0.5:
        s.append("pos")
    else:
        s.append("neg")
count = np.sum(s == test1000['情感'])
print('准确率为：',count/len(s))

准确率为： 0.9531109107303878

In [5]:
confusion_matrix = pd.crosstab(test1000['情感'], s, margins=True)  # 制作混淆矩阵
confusion_matrix

col_0  neg   pos   All
情感
neg     54    40    94
pos     12  1003  1015
All     66  1043  1109

In [6]:
print('基于SnowNLP的情感分析的准确率为：',(confusion_matrix.iat[0,0] + confusion_matrix.iat[1,1])/confusion_matrix.iat[2,2])

基于SnowNLP的情感分析的准确率为： 0.9531109107303878

# 对所有数据进行情感标注

In [7]:
reviews = pd.read_excel('./review/reviews_drdu.xlsx')
score = []
sent = []
for c in reviews['评论']:
    sc = SnowNLP(c).sentiments
    score.append(sc)
    if sc>=0.6:
        sent.append("pos")
    elif sc<=0.4:
        sent.append("neg")
    else:
        sent.append("mid")

In [9]:
reviews['score'] = score
reviews['sentiment'] = sent
reviews.to_csv('./sentiment/content_sentiment.xlsx', index = False, encoding = 'utf-8') # 导出标记情感标签的评论数据

In [10]:
neg = reviews[reviews['sentiment'].str.contains('neg')]

#重新编号
neg = neg.reset_index(drop=True)
neg

,商品名称,评价星级,评论,score,sentiment
0,iPad 10,star3,包装脏\n别的都没事服务也挺好\n,0.239992,neg
1,iPad 10,star5,京东苹果自营旗舰店双十一做活动价格很便宜，当天下单快递第二天就到了，快递发的是京东快递，平板...,0.277069,neg
2,iPad 10,star5,为了换取新的设备，我原本打算等待国际补贴的优惠。当时，如果放弃这个优惠，加上以旧换新补贴，我...,0.087602,neg
3,iPad 10,star5,应该是正品，物流速度很快，基本2天内就到了，现在东西都在网上上买了，非常的便捷。唯一盒子有点...,0.321247,neg
4,iPad 10,star5,平板还不错，发货也挺快，晚上下单的，第二天早上就收到了，就是外包装盒有好几处磕碰，不知道是快...,0.025507,neg
...,...,...,...,...,...
481,小米Redmi Pad SE,star5,可以说是还行，性价比挺高的。我以为分辨率会是老人机，没想到不是耶。还挺清晰。刷剧，给小孩玩儿...,0.072710,neg
482,小米Redmi Pad SE,star5,用了一些天，目前运行速度还是可以的，没有卡顿的情况，色彩搭配艳丽，非常赏心悦目。就是一些操作...,0.151101,neg
483,小米Redmi Pad SE,star5,挺好的，特意用了几天再来评价，冲一次电需要三个多小时，但是可以管几天，自己买了一个壳和膜，有...,0.016600,neg
484,小米Redmi Pad SE,star3,一般般，比我用了6年的iPad还卡\n,0.341517,neg
485,小米Redmi Pad SE,star5,东西是好东西，价格有国补，也是好价格，送货也很快，唯一不爽就是这个激活太麻烦了，第一天有一单...,0.000464,neg

In [11]:
pos = reviews[reviews['sentiment'].str.contains('pos')]

#重新编号
pos = pos.reset_index(drop=True)
pos

,商品名称,评价星级,评论,score,sentiment
0,iPad 10,star3,看着用着应该不错，用用看呗\n,0.964987,pos
1,iPad 10,star3,还是比较满意吧，就是质量希望多多把关\n,0.711497,pos
2,iPad 10,star3,不用多说什么，性价比高，不断提升中。\n,0.988649,pos
3,iPad 10,star5,平板非常好用系统也很流畅外观材质：蓝色，手感棒，质感\n好，特别的喜欢这个平板电脑，买电脑只...,1.000000,pos
4,iPad 10,star5,超级漂亮，女儿很喜欢，买的254的，运行速度相当可以，作为给女儿的生日礼物爱不释手，唯一一款...,1.000000,pos
...,...,...,...,...,...
15939,小米Redmi Pad SE,star5,好用，屏幕很大，用来看课很不错，非常棒的平板，质量也可以，目前没发现什么问题。客服也很耐心，...,0.999980,pos
15940,小米Redmi Pad SE,star5,商品质量无可挑剔，价格亲民，真是物超所值。物流顺畅，商家服务贴心，售后有保障，太棒了！质量很...,1.000000,pos
15941,小米Redmi Pad SE,star5,手感很好，画质触感也不错，之前买了个400多的，准备给老人看戏用，质量差，不好用，换了红米之...,0.999086,pos
15942,小米Redmi Pad SE,star5,redmi的产品性价比确实不错👍，叠加国补，这款pad不到900，这个价格性能只能说是够用了...,0.999859,pos
15943,小米Redmi Pad SE,star5,我已经向我的朋友们推荐了这款产品，因为它真的非常棒！它不仅有着卓越的性能，而且非常易于使用。...,0.999975,pos

# 绘制词云图

In [ ]:
# 绘制词云

# 正面情感词词云
freq_pos = posdata.groupby(by = ['word'])['word'].count() # 计算个分词出现次数
freq_pos = freq_pos.sort_values(ascending = False) # 降序排列
backgroud_Image=plt.imread('./data/pl.jpg')
wordcloud = WordCloud(font_path="./simhei.ttf",
                      max_words=100,
                      background_color='white',
                      mask=backgroud_Image)
pos_wordcloud = wordcloud.fit_words(freq_pos)
plt.imshow(pos_wordcloud)
plt.axis('off') 
plt.show()

In [ ]:
# 负面情感词词云
freq_neg = negdata.groupby(by = ['word'])['word'].count()
freq_neg = freq_neg.sort_values(ascending = False)
neg_wordcloud = wordcloud.fit_words(freq_neg)
plt.imshow(neg_wordcloud)
plt.axis('off') 
plt.show()