In [1]:
import pandas as pd # 以pd别名导入Python数据分析模块
import re # 导入正则表达式模块，可进行模式匹配、搜索和替换
import numpy as np # 导入数值计算模块
from sklearn.model_selection import train_test_split

In [2]:
reviews = pd.read_csv('./review/reviews_cut.csv')

# 苹果评论

In [3]:
apple = reviews[reviews['商品名称'].str.contains('iPad')]

#重新编号
apple = apple.reset_index(drop=True)
apple

,商品名称,评价星级,评论,score,sentiment,cutword
0,iPad 10,star3,包装脏别的都没事服务也挺好,0.239992,neg,包装 脏 没事 服务 挺
1,iPad 10,star3,看着用着应该不错，用用看呗,0.964987,pos,看着 不错 用用
2,iPad 10,star3,还是比较满意吧，就是质量希望多多把关,0.711497,pos,比较满意 质量 希望 把关
3,iPad 10,star3,还可以吧，追剧时候有一点点卡，还在摸索中,0.502181,mid,追剧 一点点 卡 摸索 中
4,iPad 10,star3,比较耗电，掉电很快！,0.518212,mid,耗电 掉电 很快
...,...,...,...,...,...,...
5496,iPad Pro 13,star5,这个我非常的喜欢，买回来儿子也非常的喜欢，送货速度非常的快，性价比非常的高，嗯，非常的不错，...,1.000000,pos,喜欢 买回来 儿子 喜欢 送货 速度 快 性价比 高 不错 感觉 运行 速度 快 外面 超市...
5497,iPad Pro 13,star5,东西不错，多次购买，很喜欢。,0.970486,pos,东西 不错 购买 喜欢
5498,iPad Pro 13,star5,还得是寸打游戏就是爽,0.919372,pos,寸 打游戏 爽
5499,iPad Pro 13,star5,速度很快，质量很高外观材质：好屏幕效果：好运行速度：好轻薄程度：好,0.999992,pos,速度 很快 质量 高 外观 材质 屏幕 效果 运行 速度 轻薄 程度
5500,iPad Pro 13,star5,非常好的一次购物，使用了一段时间后，真的非常满意！首先，外观设计简洁大方，质感很好，完全符合...,1.000000,pos,购物 一段时间 真的 满意 外观设计 简洁 大方 质感 完全符合 审美 功能 实用 操作 简...

In [4]:
apple.to_csv('./review/apple.csv', index = False, encoding = 'utf-8')

In [5]:
# 仅选取苹果的分词
applectwd = apple["cutword"]
applectwd.to_csv('./review/apple_cutword.csv', index = False, header = None, encoding = 'utf-8')

In [6]:
# 按市场占比随机抽取苹果的评论

# 将特征（数据）划分到 X 中，标签划分到 Y 中
x = apple[["商品名称", "评价星级", "评论", "cutword"]]
y = apple["sentiment"]
# 使用train_test_split函数划分数据集(训练集占xx%，测试集(此处为市场占比)占82.35%)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8235, random_state=0)

In [7]:
apple_test = x_test
apple_test["sentiment"] = y_test
apple_test

,商品名称,评价星级,评论,cutword,sentiment
3629,iPad mini (A17 Pro),star5,外观与设计 延续了前代产品的设计语言，整体外观简洁大方。它配备了.英寸的 显示屏，虽然屏幕边...,外观 设计 延续 前代 产品 设计 语言 整体 外观 简洁 大方 配备 英寸 显示屏 屏幕 ...,pos
142,iPad 10,star5,、宝贝真的很好很好呀，棒棒的，没有色差，没有质量问题，客服的服务态度也很好啊，物流也给力，喜...,宝贝 真的 棒棒 色差 质量 客服 服务态度 物流 力 喜欢 亲 赶紧 下单 值得 值得 下单 呐,pos
1367,iPad 9,star5,性价比不错，除了黑边属实大了点，其他各方面还是没得说的，运行很流畅，送充电器这个就比果机好很...,性价比 不错 黑 属实 没得说的 运行 流畅 送 充电器 比果 机好 验 全新 未激活 正品...,pos
4646,iPad Pro 13,star5,外观材质：好运行速度：好屏幕效果：轻薄程度：好其他特色：嗯,外观 材质 运行 速度 屏幕 效果 轻薄 程度 特色,pos
3568,iPad mini (A17 Pro),star5,发货的物流很快，然后开箱后很完整，没有任何瑕疵，的这款版的，颜值看起来很好，然后屏幕也相当的...,发货 物流 很快 开箱 完整 瑕疵 这款 颜值 屏幕 美观 携带 角度看 平整 适合 在校 大学生,pos
...,...,...,...,...,...
3215,iPad mini (A17 Pro),star5,真心喜欢，颜色、款式都非常棒！宝贝收到，物流很快，描述相符，比较满意，好评，推荐宝贝非常棒，...,真心 喜欢 颜色 款式 棒 宝贝 收到 物流 很快 描述 相符 比较满意 好评 推荐 宝贝 ...,pos
2581,iPad Air 11,star5,比较了还有的，还得是，不是果粉，真的是运行流畅，画质好，不卡不顿，这是第三个的了，之前的都用...,果粉 真的 运行 流畅 画质 不卡 不顿 这是 第三个 五年,pos
243,iPad 10,star5,回来了，上面感觉很不错，很丝滑，很喜欢。快递也很快。快递服务也不错。现在在公司，的颜色和色彩...,回来 感觉 不错 很丝滑 喜欢 快递 很快 快递 服务 不错 公司 颜色 色彩 饱和度 壳 适配,pos
4497,iPad Pro 11,star5,没有最好，只有更好！产品一如既往！,更好 产品 一如既往,pos
3543,iPad mini (A17 Pro),star5,蜂窝的跟的一个价格了，联通还送果断入手蜂窝版，内存和硬盘变大了，但竖屏果冻依旧，手游利器，很...,蜂窝 价格 联通 送 果断 入手 蜂窝 内存 硬盘 变大 竖屏 果冻 依旧 手游 利器 不错,pos

In [8]:
# apple_test.to_csv('./review/apple_test.csv', index = False, encoding = 'utf-8')

# 小米评论

In [9]:
xiaomi = reviews[reviews['商品名称'].str.contains('小米')]

#重新编号
xiaomi = xiaomi.reset_index(drop=True)
xiaomi

,商品名称,评价星级,评论,score,sentiment,cutword
0,小米6,star5,外观材质：正品店铺，放心购买，客服态度也很，整个购物过程非常顺利！下次还会再来的！赞！屏幕效...,1.000000,pos,外观 材质 正品 店铺 放心 购买 客服 态度 购物 过程 顺利 下次 还会 赞 屏幕 效果...
1,小米6,star5,这，真是太香了！屏幕清晰、操作流畅，看剧玩游戏都超爽。而且它的续航能力也是一流的，充一次电就...,0.999992,pos,真是太 香 屏幕 清晰 操作 流畅 看剧 玩游戏 超爽 续航 能力 一流 充 电 好久 再也 电量
2,小米6,star5,很好用 非常好 屏幕很大，质量也很好，摄像头拍摄较为清晰，就是感觉笔的俩功能键额外突出很丑，...,0.997930,pos,屏幕 很大 质量 摄像头 拍摄 清晰 感觉 笔 俩 功能键 额外 很丑 功能 单一 用处
3,小米6,star5,收到了，十分捧的质感，太喜欢这个色了，界面简洁好用，操作方便，屏幕清晰度高，超赞。,0.981969,pos,收到 捧 质感 太 喜欢 色 界面 简洁 好用 操作 屏幕 清晰度 高 超赞
4,小米6,star5,外观材质：外观漂亮，大气，，手感很棒。屏幕效果：屏幕很细腻，通透性很好。运行速度：运行速度嘎...,1.000000,pos,外观 材质 外观 漂亮 大气 手感 很棒 屏幕 效果 屏幕 细腻 通透性 运行 速度 运行 ...
...,...,...,...,...,...,...
4892,小米Redmi Pad SE,star5,好用，屏幕很大，用来看课很不错，非常棒的，质量也可以，目前没发现什么问题。客服也很耐心，解答...,0.999980,pos,好用 屏幕 很大 课 不错 棒 质量 没 发现 客服 耐心 解答 外观 高大 速度
4893,小米Redmi Pad SE,star5,商品质量无可挑剔，价格亲民，真是物超所值。物流顺畅，商家服务贴心，售后有保障，太棒了！质量很...,1.000000,pos,商品质量 无可挑剔 价格 亲民 物超所值 物流 顺畅 商家 服务 贴心 售后 保障 太棒了 ...
4894,小米Redmi Pad SE,star5,手感很好，画质触感也不错，之前买了个多的，准备给老人看戏用，质量差，不好用，换了红米之后 很...,0.999086,pos,手感 画质 触感 不错 老人 看戏用 质量 差 不好 换 红米 顺滑 流畅 度高 满意
4895,小米Redmi Pad SE,star5,的产品性价比确实不错，叠加国补，这款不到，这个价格性能只能说是够用了，显示屏不是高清的，颗粒...,0.999859,pos,产品 性价比 确实 不错 叠加 国补 不到 价格 性能 只能 说 够用 显示屏 高清 颗粒感
4896,小米Redmi Pad SE,star5,我已经向我的朋友们推荐了这款产品，因为它真的非常棒！它不仅有着卓越的性能，而且非常易于使用。...,0.999975,pos,朋友 推荐 这款 产品 真的 棒 卓越 性能 易于 价格 真的 物超所值

In [10]:
xiaomi.to_csv('./review/xiaomi.csv', index = False, encoding = 'utf-8')

In [11]:
# 仅选取小米分词
xiaomictwd = xiaomi["cutword"]
xiaomictwd.to_csv('./review/xiaomi_cutword.csv', index = False, header = None, encoding = 'utf-8')

In [12]:
# 按市场占比随机抽取xiaomi的评论

# 将特征（数据）划分到 u 中，标签划分到 v 中
u = xiaomi[["商品名称", "评价星级", "评论", "cutword"]]
v = xiaomi["sentiment"]
# 使用train_test_split函数划分数据集(训练集占xx%，测试集(此处为市场占比)占41.80%)
u_train, u_test, v_train, v_test = train_test_split(u, v, test_size=0.3932, random_state=0)

In [13]:
xiaomi_test = u_test
xiaomi_test["sentiment"] = v_test
xiaomi_test

,商品名称,评价星级,评论,cutword,sentiment
2762,小米7Pro,star5,外观材质：绿色很好看很清新的感觉运行速度：还是比较丝滑的好用轻薄程度：拿起来很清，体验感很不错,外观 材质 绿色 好看 清新 感觉 运行 速度 丝滑 轻薄 程度 很清 体验 感 不错,pos
42,小米6,star5,是一款备受瞩目的，其简洁大方的包装设计让人心生好感。金色版本的版本虽然没有那么奢华，但也足够...,备受瞩目 简洁 大方 包装 设计 人心 生 好感 金色 版本 版本 奢华 足够 日常 系统 ...,pos
1419,小米7,star5,性能卓越，设计简约，.屏幕素质很高，非常清晰，观影体验极佳，还有生态互联，性价比拉满，使用体...,性能 卓越 设计 简约 屏幕 素质 高 清晰 观影 体验 极佳 生态 互联 性价比 拉满 体...,pos
3664,小米Redmi Pad Pro,star5,红米 太棒了！外观简约时尚，轻薄便携。屏幕显示清晰，色彩鲜艳，追剧超爽。性能稳定，日常学习办...,红米 太棒了 外观 简约 时尚 轻薄 便携 屏幕显示 清晰 色彩鲜艳 追剧 超爽 性能 稳定...,pos
2125,小米7,star5,国补买的，还算便宜，包裹严实，打开后画质很好，也很轻薄，孩子很喜欢。快递小哥服务态度非常好，...,国补 算 便宜 包裹 严实 打开 画质 轻薄 孩子 喜欢 快递 小哥 服务态度 冷天 耐心 ...,pos
...,...,...,...,...,...
4156,小米Redmi Pad SE,star5,价格实惠，运行速度快，小孩子学习用足够，价格实惠，活动力度很大，钢化膜质量好，值得购买欲望都...,价格 实惠 运行 速度 快 小孩子 学习 足够 价格 实惠 活动 力度 很大 钢化 膜 质量...,pos
4434,小米Redmi Pad SE,star5,这款红米 一是双 的时候下单购买的，双 的价格非常给力，比平时降价了不少。 的存储空间适合老...,这款 红米 一是 双 下单 购买 双 价格 给力 平时 降价 存储空间 适合 老人 看剧 机...,neg
3710,小米Redmi Pad Pro,star5,外观材质：做工精细屏幕效果：颜色亮丽运行速度：刚刚地轻薄程度：适手其他特色：使用方便音质音效...,外观 材质 做工 精细 屏幕 效果 颜色 亮丽 运行 速度 刚刚 轻薄 程度 适手 特色 使...,pos
703,小米6Pro,star5,全金属外壳摸上去非常有质感操作体验很丝滑，跟几乎没差价格非常香续航很强，昨晚打了两个多小时王...,全 金属外壳 摸上去 质感 操作 体验 很丝滑 没差 价格 香 续航 很强 昨晚 两个 小时...,pos
369,小米6Max,star5,的这个性价比真的超级高了，包装精美，物流配送第二天就收到了。手感不错，买来刷视频看的，很耐用...,性价比 真的 超级 高 包装 精美 物流配送 第二天 收到 手感 不错 刷 视频 耐用 反应...,pos

In [14]:
# xiaomi_test.to_csv('./review/xiaomi_test.csv', index = False, encoding = 'utf-8')

# 华为评论

In [15]:
huawei = reviews[reviews['商品名称'].str.contains('Mate')]

#重新编号
huawei = huawei.reset_index(drop=True)
huawei

,商品名称,评价星级,评论,score,sentiment,cutword
0,MatePad 11.5,star5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,0.999985,pos,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳
1,MatePad 11.5,star5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,1.000000,pos,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...
2,MatePad 11.5,star5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,0.994186,pos,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作
3,MatePad 11.5,star5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,1.000000,pos,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...
4,MatePad 11.5,star5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,1.000000,pos,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...
...,...,...,...,...,...,...
6153,MatePad SE 11,star5,买的速度快，有保障，国产品牌，我骄傲，买回来给小孩学习用的，不会卡，速度快，内存容量也够用，...,0.999998,pos,速度 快 保障 国产品牌 骄傲 买回来 小孩 学习 卡 速度 快 内存容量 够用 好用
6154,MatePad SE 11,star5,用了觉得很不错，商品质量好，发货也挺快的，总之就是很赞了本来还很担心东西不好，拿到手发现完全...,0.999999,pos,不错 商品质量 发货 挺快 很赞 本来 担心 东西 不好 拿到 发现 多虑 五星 好评 理想...
6155,MatePad SE 11,star5,这个价位购买学习设备非常划算，大屏幕清晰度很高，对眼睛也很友好。使用了一段时间，没有出现卡顿...,0.999623,pos,价位 购买 学习 设备 划算 大屏幕 清晰度 高 眼睛 友好 一段时间 卡顿 现象 适合 小...
6156,MatePad SE 11,star5,非常不错，一直在用，这是第三个了，无论是刷剧，上网还是游戏，特别是小孩学习用，操作顺滑不卡顿...,0.999999,pos,不错 这是 第三个 刷剧 上网 游戏 特别 小孩 学习 操作 顺滑 不卡顿 价格 实惠 总体 不错
6157,MatePad SE 11,star5,很好用哟的，听歌，做作业都好用，运行速度也好，很轻薄，使用感不错，会持续购买的音质音效：很好...,1.000000,pos,听歌 做作业 运行 速度 轻薄 感 不错 持续 购买 音质 音效 听歌 安逸 轻薄 程度 精...

In [16]:
huawei.to_csv('./review/huawei.csv', index = False, encoding = 'utf-8')

In [17]:
# 仅选取华为分词
huaweictwd = huawei["cutword"]
huaweictwd.to_csv('./review/huawei_cutword.csv', index = False, header = None, encoding = 'utf-8')

# 合并抽取好的3个品牌数据

In [18]:
huawei_sentiment = huawei["sentiment"]

In [19]:
huawei_test = huawei.drop(columns=['score','sentiment'])
huawei_test

,商品名称,评价星级,评论,cutword
0,MatePad 11.5,star5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳
1,MatePad 11.5,star5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...
2,MatePad 11.5,star5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作
3,MatePad 11.5,star5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...
4,MatePad 11.5,star5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...
...,...,...,...,...
6153,MatePad SE 11,star5,买的速度快，有保障，国产品牌，我骄傲，买回来给小孩学习用的，不会卡，速度快，内存容量也够用，...,速度 快 保障 国产品牌 骄傲 买回来 小孩 学习 卡 速度 快 内存容量 够用 好用
6154,MatePad SE 11,star5,用了觉得很不错，商品质量好，发货也挺快的，总之就是很赞了本来还很担心东西不好，拿到手发现完全...,不错 商品质量 发货 挺快 很赞 本来 担心 东西 不好 拿到 发现 多虑 五星 好评 理想...
6155,MatePad SE 11,star5,这个价位购买学习设备非常划算，大屏幕清晰度很高，对眼睛也很友好。使用了一段时间，没有出现卡顿...,价位 购买 学习 设备 划算 大屏幕 清晰度 高 眼睛 友好 一段时间 卡顿 现象 适合 小...
6156,MatePad SE 11,star5,非常不错，一直在用，这是第三个了，无论是刷剧，上网还是游戏，特别是小孩学习用，操作顺滑不卡顿...,不错 这是 第三个 刷剧 上网 游戏 特别 小孩 学习 操作 顺滑 不卡顿 价格 实惠 总体 不错
6157,MatePad SE 11,star5,很好用哟的，听歌，做作业都好用，运行速度也好，很轻薄，使用感不错，会持续购买的音质音效：很好...,听歌 做作业 运行 速度 轻薄 感 不错 持续 购买 音质 音效 听歌 安逸 轻薄 程度 精...

In [20]:
huawei_test.insert(3, 'sentiment', huawei_sentiment, True)
huawei_test

,商品名称,评价星级,评论,sentiment,cutword
0,MatePad 11.5,star5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,pos,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳
1,MatePad 11.5,star5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,pos,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...
2,MatePad 11.5,star5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,pos,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作
3,MatePad 11.5,star5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,pos,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...
4,MatePad 11.5,star5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,pos,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...
...,...,...,...,...,...
6153,MatePad SE 11,star5,买的速度快，有保障，国产品牌，我骄傲，买回来给小孩学习用的，不会卡，速度快，内存容量也够用，...,pos,速度 快 保障 国产品牌 骄傲 买回来 小孩 学习 卡 速度 快 内存容量 够用 好用
6154,MatePad SE 11,star5,用了觉得很不错，商品质量好，发货也挺快的，总之就是很赞了本来还很担心东西不好，拿到手发现完全...,pos,不错 商品质量 发货 挺快 很赞 本来 担心 东西 不好 拿到 发现 多虑 五星 好评 理想...
6155,MatePad SE 11,star5,这个价位购买学习设备非常划算，大屏幕清晰度很高，对眼睛也很友好。使用了一段时间，没有出现卡顿...,pos,价位 购买 学习 设备 划算 大屏幕 清晰度 高 眼睛 友好 一段时间 卡顿 现象 适合 小...
6156,MatePad SE 11,star5,非常不错，一直在用，这是第三个了，无论是刷剧，上网还是游戏，特别是小孩学习用，操作顺滑不卡顿...,pos,不错 这是 第三个 刷剧 上网 游戏 特别 小孩 学习 操作 顺滑 不卡顿 价格 实惠 总体 不错
6157,MatePad SE 11,star5,很好用哟的，听歌，做作业都好用，运行速度也好，很轻薄，使用感不错，会持续购买的音质音效：很好...,pos,听歌 做作业 运行 速度 轻薄 感 不错 持续 购买 音质 音效 听歌 安逸 轻薄 程度 精...

In [21]:
reviews_extracted = pd.concat([huawei_test, apple_test, xiaomi_test])
reviews_extracted = reviews_extracted.reset_index(drop=True)
reviews_extracted

,商品名称,评价星级,评论,sentiment,cutword
0,MatePad 11.5,star5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,pos,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳
1,MatePad 11.5,star5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,pos,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...
2,MatePad 11.5,star5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,pos,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作
3,MatePad 11.5,star5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,pos,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...
4,MatePad 11.5,star5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,pos,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...
...,...,...,...,...,...
12610,小米Redmi Pad SE,star5,价格实惠，运行速度快，小孩子学习用足够，价格实惠，活动力度很大，钢化膜质量好，值得购买欲望都...,pos,价格 实惠 运行 速度 快 小孩子 学习 足够 价格 实惠 活动 力度 很大 钢化 膜 质量...
12611,小米Redmi Pad SE,star5,这款红米 一是双 的时候下单购买的，双 的价格非常给力，比平时降价了不少。 的存储空间适合老...,neg,这款 红米 一是 双 下单 购买 双 价格 给力 平时 降价 存储空间 适合 老人 看剧 机...
12612,小米Redmi Pad Pro,star5,外观材质：做工精细屏幕效果：颜色亮丽运行速度：刚刚地轻薄程度：适手其他特色：使用方便音质音效...,pos,外观 材质 做工 精细 屏幕 效果 颜色 亮丽 运行 速度 刚刚 轻薄 程度 适手 特色 使...
12613,小米6Pro,star5,全金属外壳摸上去非常有质感操作体验很丝滑，跟几乎没差价格非常香续航很强，昨晚打了两个多小时王...,pos,全 金属外壳 摸上去 质感 操作 体验 很丝滑 没差 价格 香 续航 很强 昨晚 两个 小时...
12614,小米6Max,star5,的这个性价比真的超级高了，包装精美，物流配送第二天就收到了。手感不错，买来刷视频看的，很耐用...,pos,性价比 真的 超级 高 包装 精美 物流配送 第二天 收到 手感 不错 刷 视频 耐用 反应...

In [22]:
reviews_extracted.to_csv('./review/reviews_extracted.csv', index = False, encoding = 'utf-8')

In [26]:
#可以通过df.colname 来指定某个列，value_count()在这里进行计数
df = reviews_extracted["评价星级"].value_counts()  
print(df)

评价星级
star5    12371
star3      134
star1       72
star2       24
star4       14
Name: count, dtype: int64