In [1]:
import pandas as pd # 以pd别名导入Python数据分析模块
import numpy as np # 导入数值计算模块

# 苹果情感聚类
## apple_pos

In [2]:
apple = pd.read_csv('./review/apple.csv')

In [3]:
apple_pos = apple[apple['sentiment'].str.contains('pos')]

# 重新编号
apple_pos = apple_pos.reset_index(drop=True)
apple_pos

,商品名称,评价星级,评论,score,sentiment,cutword
0,iPad 10,star3,包装脏别的都没事服务也挺好,0.741751,pos,包装 脏 没事 服务 挺
1,iPad 10,star3,看着用着应该不错，用用看呗,0.969298,pos,看着 不错 用用
2,iPad 10,star3,还是比较满意吧，就是质量希望多多把关,0.659414,pos,比较满意 质量 希望 把关
3,iPad 10,star3,不用多说什么，性价比高，不断提升中。,0.995384,pos,不用 说 性价比 高 提升 中
4,iPad 10,star5,非常好用系统也很流畅外观材质：蓝色，手感棒，质感好，特别的喜欢这个，买只信赖商城的的产品。屏...,1.000000,pos,好用 系统 流畅 外观 材质 蓝色 手感 棒 质感 特别 喜欢 信赖 商城 产品 屏幕 效果...
...,...,...,...,...,...,...
4638,iPad Pro 13,star5,外观材质：的产品使用一直很不错屏幕效果：感觉比我的的屏幕效果好很多运行速度：的芯片比我的芯片...,1.000000,pos,外观 材质 产品 不错 屏幕 效果 感觉 屏幕 效果 运行 速度 芯片 芯片 提升 一半 轻...
4639,iPad Pro 13,star5,这个我非常的喜欢，买回来儿子也非常的喜欢，送货速度非常的快，性价比非常的高，嗯，非常的不错，...,1.000000,pos,喜欢 买回来 儿子 喜欢 送货 速度 快 性价比 高 不错 感觉 运行 速度 快 外面 超市...
4640,iPad Pro 13,star5,东西不错，多次购买，很喜欢。,0.999299,pos,东西 不错 购买 喜欢
4641,iPad Pro 13,star5,速度很快，质量很高外观材质：好屏幕效果：好运行速度：好轻薄程度：好,1.000000,pos,速度 很快 质量 高 外观 材质 屏幕 效果 运行 速度 轻薄 程度
4642,iPad Pro 13,star5,非常好的一次购物，使用了一段时间后，真的非常满意！首先，外观设计简洁大方，质感很好，完全符合...,1.000000,pos,购物 一段时间 真的 满意 外观设计 简洁 大方 质感 完全符合 审美 功能 实用 操作 简...

In [4]:
apple_pos.to_csv('./sentiment/apple_pos.csv', index = False, encoding = 'utf-8')

## apple_neg

In [5]:
apple_neg = apple[apple['sentiment'].str.contains('neg')]

# 重新编号
apple_neg = apple_neg.reset_index(drop=True)
apple_neg

,商品名称,评价星级,评论,score,sentiment,cutword
0,iPad 10,star3,还可以吧，追剧时候有一点点卡，还在摸索中,0.111730,neg,追剧 一点点 卡 摸索 中
1,iPad 10,star3,比较耗电，掉电很快！,0.000735,neg,耗电 掉电 很快
2,iPad 10,star5,自营旗舰店双十一做活动价格很便宜，当天下单快递第二天就到了，快递发的是快递，系统很流畅不卡顿...,0.324642,neg,自营 旗舰店 双十 一做 活动 价格 便宜 当天 下单 快递 第二天 快递 发 快递 系统 ...
3,iPad 10,star5,在双活动期间，我购买了一款全新未拆封、未激活的产品，价格相较于其他平台更为优惠。这次购物体验...,0.002195,neg,双 活动 期间 购买 全新 未 拆封 未激活 产品 价格 相较 平台 优惠 购物 体验 愉快...
4,iPad 10,star4,整体还不错，刚拿到手很担心有瑕疵，结果打开发现外观完美，好多年不玩了，最早买过的还是，拿到手...,0.000008,neg,整体 不错 刚 拿到 担心 瑕疵 打开 发现 外观 完美 好多年 不玩 最早 买过 拿到 没...
...,...,...,...,...,...,...
766,iPad Pro 13,star5,很好用。芯片贼顺畅。 是 ，是。这话没错。叠劵，比线下便宜了一千一百多到手，就买了个轻松，很划算,0.016602,neg,芯片 贼 顺畅 这话 没错 叠 劵 线下 便宜 一千一百 到手 轻松 划算
767,iPad Pro 13,star1,辣鸡售后服务，买错了型号不给换,0.000007,neg,辣鸡 售后服务 买错 型号 换
768,iPad Pro 13,star5,最开始买的是，，不是很爽，退了换了，果然惊艳，外箱包装没有任何信息，很隐私很保密，做得不错！,0.001192,neg,很爽 退 换 惊艳 外箱 包装 信息 隐私 保密 做 不错
769,iPad Pro 13,star5,快递真给力啊！两天就收到了！,0.137426,neg,快递 真给力 两天 收到
770,iPad Pro 13,star5,还得是寸打游戏就是爽,0.308708,neg,寸 打游戏 爽

In [6]:
apple_neg.to_csv('./sentiment/apple_neg.csv', index = False, encoding = 'utf-8')

# 小米情感聚类
## xiaomi_pos

In [7]:
xiaomi = pd.read_csv('./review/xiaomi.csv')

In [8]:
xiaomi_pos = xiaomi[xiaomi['sentiment'].str.contains('pos')]

# 重新编号
xiaomi_pos = xiaomi_pos.reset_index(drop=True)
xiaomi_pos

,商品名称,评价星级,评论,score,sentiment,cutword
0,小米6,star5,外观材质：正品店铺，放心购买，客服态度也很，整个购物过程非常顺利！下次还会再来的！赞！屏幕效...,1.000000,pos,外观 材质 正品 店铺 放心 购买 客服 态度 购物 过程 顺利 下次 还会 赞 屏幕 效果...
1,小米6,star5,这，真是太香了！屏幕清晰、操作流畅，看剧玩游戏都超爽。而且它的续航能力也是一流的，充一次电就...,0.993843,pos,真是太 香 屏幕 清晰 操作 流畅 看剧 玩游戏 超爽 续航 能力 一流 充 电 好久 再也 电量
2,小米6,star5,很好用 非常好 屏幕很大，质量也很好，摄像头拍摄较为清晰，就是感觉笔的俩功能键额外突出很丑，...,0.999181,pos,屏幕 很大 质量 摄像头 拍摄 清晰 感觉 笔 俩 功能键 额外 很丑 功能 单一 用处
3,小米6,star5,收到了，十分捧的质感，太喜欢这个色了，界面简洁好用，操作方便，屏幕清晰度高，超赞。,0.999979,pos,收到 捧 质感 太 喜欢 色 界面 简洁 好用 操作 屏幕 清晰度 高 超赞
4,小米6,star5,外观材质：外观漂亮，大气，，手感很棒。屏幕效果：屏幕很细腻，通透性很好。运行速度：运行速度嘎...,1.000000,pos,外观 材质 外观 漂亮 大气 手感 很棒 屏幕 效果 屏幕 细腻 通透性 运行 速度 运行 ...
...,...,...,...,...,...,...
4451,小米Redmi Pad SE,star5,的做得非常好，国产内存做得最优秀的了，内存也不错运行不卡下下闪到小孩很喜欢爱不释手，从来舍不...,1.000000,pos,做 国产 内存 做 优秀 内存 不错 运行 不卡下 闪到 小孩 喜欢 爱不释手 舍不得 放下...
4452,小米Redmi Pad SE,star5,好用，屏幕很大，用来看课很不错，非常棒的，质量也可以，目前没发现什么问题。客服也很耐心，解答...,1.000000,pos,好用 屏幕 很大 课 不错 棒 质量 没 发现 客服 耐心 解答 外观 高大 速度
4453,小米Redmi Pad SE,star5,商品质量无可挑剔，价格亲民，真是物超所值。物流顺畅，商家服务贴心，售后有保障，太棒了！质量很...,1.000000,pos,商品质量 无可挑剔 价格 亲民 物超所值 物流 顺畅 商家 服务 贴心 售后 保障 太棒了 ...
4454,小米Redmi Pad SE,star5,手感很好，画质触感也不错，之前买了个多的，准备给老人看戏用，质量差，不好用，换了红米之后 很...,1.000000,pos,手感 画质 触感 不错 老人 看戏用 质量 差 不好 换 红米 顺滑 流畅 度高 满意
4455,小米Redmi Pad SE,star5,我已经向我的朋友们推荐了这款产品，因为它真的非常棒！它不仅有着卓越的性能，而且非常易于使用。...,1.000000,pos,朋友 推荐 这款 产品 真的 棒 卓越 性能 易于 价格 真的 物超所值

In [9]:
xiaomi_pos.to_csv('./sentiment/xiaomi_pos.csv', index = False, encoding = 'utf-8')

## xiaomi_neg

In [10]:
xiaomi_neg = xiaomi[xiaomi['sentiment'].str.contains('neg')]

# 重新编号
xiaomi_neg = xiaomi_neg.reset_index(drop=True)
xiaomi_neg

,商品名称,评价星级,评论,score,sentiment,cutword
0,小米6,star5,很棒，本来犹豫是在线下买还是线上买，刚好碰到百亿补贴，毫不犹豫的下手了，物流隔天到，体验感非...,1.587572e-01,neg,很棒 本来 犹豫 在线 下买 线上 碰到 百亿 补贴 毫不犹豫 下手 物流 隔天 体验 感 ...
1,小米6,star5,一次去商场在展柜看到的这款机器，当时也是配着键盘，感觉偶尔用来轻办公应该也不错，后来就在入手...,2.825296e-02,neg,商场 展柜 这款 机器 配着 键盘 感觉 轻 办公 不错 入手 赶上 活动 价格 挺不错 屏...
2,小米6,star5,价格特别便宜，送货也快，自营上面颜色也比较全，版本也全，想买哪个就买哪个，不像店里边。去了不...,2.244462e-05,neg,价格 特别 便宜 送货 快 自营 颜色 全 版本 全 想 不像 店里 没货 没货 货 想要 ...
3,小米6,star5,有三个音响，音质清晰，无杂音。充电器，充电超快。前后摄像录像清晰度高。前摄像头放置中间位置，...,1.524576e-01,neg,三个 音响 音质 清晰 杂音 充电器 充电 超快 摄像 录像 清晰度 高 前 摄像头 放置 ...
4,小米6,star5,一开始看了评论区的差评还有点犹豫要不要买这个 我不太懂什么性能这个是一个学弟推荐的 说性价比...,4.885946e-08,neg,评论 区 差评 犹豫 太 懂 性能 学弟 推荐 说 性价比 高 反正 感觉 挺好用 评论 区...
...,...,...,...,...,...,...
388,小米Redmi Pad SE,star5,红米收到了，英寸，高刷高清屏，，补贴价买的，特别香。下单第二天中午就收到了，日常使用，轻度...,3.721119e-01,neg,红米 收到 英寸 高刷 高 清屏 补贴 价买 特别 香 下单 第二天 中午 收到 日常 轻...
389,小米Redmi Pad SE,star5,快递很快，安全可靠，当天拍下当天就送到了。等着用，刚好用上。没赶上国补贴有点遗憾，希望以后多...,8.267688e-04,neg,快递 很快 安全可靠 当天 拍 当天 送到 没 赶上 国 补贴 遗憾 希望 搞 活动 屏幕 ...
390,小米Redmi Pad SE,star5,果脯期间下单叠加了的会员优惠，感觉非常合适。到的很快，下单后第天就送到了。而且因为用了国补，...,3.623033e-01,neg,果脯 期间 下单 叠加 会员 优惠 感觉 合适 很快 下单 第天 送到 国补 小哥 当面 激...
391,小米Redmi Pad SE,star5,"红米的这款,可以说性价比比较高的。以前买过的，好几千块。这个功能不比差多少，但价钱便宜好多。...",9.358322e-02,neg,红米 这款 说 性价比 高 买过 几千块 功能 不比差 价钱 便宜 好多 日常 推荐
392,小米Redmi Pad SE,star5,的产品性价比确实不错，叠加国补，这款不到，这个价格性能只能说是够用了，显示屏不是高清的，颗粒...,2.682297e-01,neg,产品 性价比 确实 不错 叠加 国补 不到 价格 性能 只能 说 够用 显示屏 高清 颗粒感

In [11]:
xiaomi_neg.to_csv('./sentiment/xiaomi_neg.csv', index = False, encoding = 'utf-8')

# 华为情感聚类
## huawei_pos

In [12]:
huawei = pd.read_csv('./review/huawei.csv')

In [13]:
huawei_pos = huawei[huawei['sentiment'].str.contains('pos')]

# 重新编号
huawei_pos = huawei_pos.reset_index(drop=True)
huawei_pos

,商品名称,评价星级,评论,score,sentiment,cutword
0,MatePad 11.5,star5,高清护眼屏，丰富的学习资源，配件可选择性强，搭配之后非常实用，给孩子辅助学习非常方便，真的被...,1.000000,pos,高清 护眼 屏 学习 资源 配件 可选择性 强 搭配 实用 孩子 辅助 学习 真的 设计 惊艳
1,MatePad 11.5,star5,还在犹豫该不该冲的学生党可以看我这边，完全真实的新机测评！!！真的是百闻不如一记！ 第一次看...,0.999909,pos,犹豫 该不该 学生 党 真实 新机 测评 真的 百闻不如 一记 第一次 麒麟 系列 快充 一...
2,MatePad 11.5,star5,今天收到宝贝，该说不说.颜值很在线 薄厚适中，手感相当的 系统运行起来比较流畅，关键是价格很...,1.000000,pos,收到 宝贝 说 说 颜值 在线 薄厚 适中 手感 系统 运行 流畅 关键 价格 亲民 声音 操作
3,MatePad 11.5,star5,外观材质：金属机身凉手哇屏幕效果：清晰通透护眼呀运行速度：麒麟芯片可以呀轻薄程度：轻薄拿着不...,1.000000,pos,外观 材质 金属 机身 凉手 屏幕 效果 清晰 通透 护眼 运行 速度 麒麟 芯片 轻薄 程...
4,MatePad 11.5,star5,外观设计漂亮，尺寸大小合适，包装仔细完整，宝贝手感不错，感觉很好，发货速度快，服务态度一流，...,1.000000,pos,外观设计 漂亮 尺寸 大小 合适 包装 仔细 完整 宝贝 手感 不错 感觉 发货 速度 快 ...
...,...,...,...,...,...,...
5660,MatePad SE 11,star5,买的速度快，有保障，国产品牌，我骄傲，买回来给小孩学习用的，不会卡，速度快，内存容量也够用，...,0.999104,pos,速度 快 保障 国产品牌 骄傲 买回来 小孩 学习 卡 速度 快 内存容量 够用 好用
5661,MatePad SE 11,star5,用了觉得很不错，商品质量好，发货也挺快的，总之就是很赞了本来还很担心东西不好，拿到手发现完全...,1.000000,pos,不错 商品质量 发货 挺快 很赞 本来 担心 东西 不好 拿到 发现 多虑 五星 好评 理想...
5662,MatePad SE 11,star5,这个价位购买学习设备非常划算，大屏幕清晰度很高，对眼睛也很友好。使用了一段时间，没有出现卡顿...,1.000000,pos,价位 购买 学习 设备 划算 大屏幕 清晰度 高 眼睛 友好 一段时间 卡顿 现象 适合 小...
5663,MatePad SE 11,star5,非常不错，一直在用，这是第三个了，无论是刷剧，上网还是游戏，特别是小孩学习用，操作顺滑不卡顿...,1.000000,pos,不错 这是 第三个 刷剧 上网 游戏 特别 小孩 学习 操作 顺滑 不卡顿 价格 实惠 总体 不错
5664,MatePad SE 11,star5,很好用哟的，听歌，做作业都好用，运行速度也好，很轻薄，使用感不错，会持续购买的音质音效：很好...,1.000000,pos,听歌 做作业 运行 速度 轻薄 感 不错 持续 购买 音质 音效 听歌 安逸 轻薄 程度 精...

In [14]:
huawei_pos.to_csv('./sentiment/huawei_pos.csv', index = False, encoding = 'utf-8')

## huawei_neg

In [15]:
huawei_neg = huawei[huawei['sentiment'].str.contains('neg')]

# 重新编号
huawei_neg = huawei_neg.reset_index(drop=True)
huawei_neg

,商品名称,评价星级,评论,score,sentiment,cutword
0,MatePad 11.5,star5,凌晨下单，下午就送到了。速度！开机前有仔细检查包装外观，应该是全新未拆封，生产日期是年月。作...,0.000011,neg,凌晨 下单 下午 送到 速度 开机 前有 仔细检查 包装 外观 全新 未 拆封 生产日期 年...
1,MatePad 11.5,star5,东西比我想象中的还要完美，十分给力，值得入手。首发买的，现在屏幕已经发黑了。正好这款发布，价...,0.242912,neg,东西 想象 中 完美 给力 值得 入手 首发 屏幕 发黑 正好 发布 价格比 便宜 拿到 手...
2,MatePad 11.5,star1,推荐的皮套严重不符合，搞得我挨退货和折损费,0.000007,neg,推荐 皮套 符合 搞 挨 退货 折损 费
3,MatePad 11.5,star5,本来还在纠结买哪款，刚好款有货，没有犹豫直接买了，柔光版看着确实舒服，分辨率也高。基本家用妥妥的,0.120151,neg,本来 纠结 哪款 货 犹豫 柔光 看着 确实 舒服 分辨率 高 家用 妥妥
4,MatePad 11.5,star5,"利用这次双十一，以出头价格，买了这款种草已久的,算是给孩子的礼物，既能寓教于乐，又能护眼，做...",0.057796,neg,利用 双十 出头 价格 这款 种草 已久 算是 孩子 礼物 寓教于乐 护眼 点赞
...,...,...,...,...,...,...
446,MatePad SE 11,star5,老爸之前用的有些老旧了，不但速度慢，电池持续时间也越来越短。趁现在有国补给老爸换个新的，外观...,0.001888,neg,老爸 老旧 速度慢 电池 持续时间 越来越 短 趁现在 有国 补给 老爸 换个 新 外观 手...
447,MatePad SE 11,star3,年前活动购买，一个月左右讲到,0.000185,neg,年前 活动 购买 一个月 讲
448,MatePad SE 11,star5,买来看剧和漫画的，真的和漫画绝配哦，超大屏看得好爽，专门等回来才看的！！！买了可爱的壳，好喜...,0.003779,neg,剧 漫画 真的 漫画 绝配 超大 屏看 好爽 回来 可爱 壳 喜欢 剧 漫画 妥妥
449,MatePad SE 11,star5,买给家里老人的。回老家时发现老爸拿着手机上书法课，屏幕太小很不方便。就从自营上给老人选了这一...,0.174328,neg,家里 老人 回老家 时 发现 老爸 手机 书法课 屏幕 太小 自营 老 人选 性价比 高
450,MatePad SE 11,star3,还可以吧，就是拍照分辨率低,0.223037,neg,拍照 分辨率 低

In [16]:
huawei_neg.to_csv('./sentiment/huawei_neg.csv', index = False, encoding = 'utf-8')